### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#1]
@maryjom suggests: Can disclaimer go to the bottom? 

Draft text: 
> The policy links on this page are compiled as a resource by the World Wide Web Consortium’s (W3C) Web Accessibility Initiative (WAI) Education and Outreach Working Group (EOWG). This page is not a comprehensive resource for all applicable laws and policies for Web accessibility. The information on this page is not legal advice. If you have questions about the applicability of the laws to specific situations, consult with legal authorities in the appropriate jurisdiction.

**Comment by nitedog** [comment]
Or collapsible or in the left navigation bar (as in the [tools list](https://www.w3.org/WAI/ER/tools/)).

**Comment by bakkenb** [comment]
I think the disclaimer is important enough to stay near the top. Could be put in a side bar. In the new re-design, I think it would be in a right hand side call out or sidebar as the left side may be reserved for sub-navigation only. All still yet to be determined.

My preference is to keep this up higher on the page.

**Comment by slhenry** [comment]
As you know, I'm generally big on disclaimers to cover our... bases. However, I think much of this is pretty obvious. I support it being less intrusive &mdash; in a sidebar &/or collapsed by default. I think it probably probably stay near the top, not go to the bottom, since this page will be very long.

Note: Anna Belle says she looks for disclaimer in footer areas, and she pushed strongly for a link to be included in the footer of the Tools List. That would be OK for me on this, too.

**Comment by yatil** [comment]
Maybe we can reword and keep it on the top as a (bold?) 1-3 sentence paragraph:

> **This list shows an overview of applicable laws and policies for web accessibility – it is _not_ comprehensive. The information is not legal advice. If you have questions about the applicability of the laws to specific situations, consult with legal authorities in the appropriate jurisdiction.**

**Comment by AndrewArch** [comment]
@slhenry on this occasion I agree that keeping it near the top is important. I do like the added suggestion of a link in the footer (if that will be a footer feature or option in the redesign)

+1 to the abbreviated version by @yatil - much sharper. My edit pass:

> This page provides an overview of applicable national laws and policies for web accessibility – it is _not_ comprehensive. The information provided is _not_ legal advice. If you have questions about the applicability of the links to specific situations, consult with legal authorities in the appropriate country.

**Comment by nitedog** [comment]
I agree to the shorter and sharper text, and to linking to it from the footer. I add to this discussion the suggestion to link to the text from the top too, and recommend that we put the in a side bar (left or right, as needed). At the very least make it collapsible. I don't see this any different to the disclaimer of the tools list in terms of potential confusion and need to have it prominent.

**Comment by hkramer** [comment]
+1 to shorter version

**Comment by AndrewArch** [comment]
@nitedog this has legal implications, so probably different from many of our other resources

**Comment by yatil** [comment]
What about:

> This is _not legal advice_. (click to open)
>
> … Full disclaimer here…

**Comment by dboudreau** [comment]
+1 to shorter version, at the top, with a link at the bottom pointing back to it.

**Comment by nitedog** [comment]
+1 to something like @yatil suggested

**Comment by AndrewArch** [comment]
yeah - the suggestion from @yatil could work

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item03). Summary:
It's visible first time, then if users collapse it, it stays collapsed on future visits.

**Comment by maryjom** [comment]
In 10 Feb telecon, we also agreed to add a link to the disclaimer in the footer. Somewhere in the top we need either the disclaimer (perhaps collapsible) or a short sentence or heading to link to the disclaimer in a sidebar and shorten the text. We need to keep it prominent but less obtrusive.

**Comment by yatil** [comment]
Feedback from the meeting – Maybe we have the disclaimer open, but allow people to close it and remember that on re-visits.

**Comment by bakkenb** [comment]
Based on meeting discussion, I too believe it would be nice to have a consistent introduction/disclaimer/information section across most pages in the site. Familiarity will help a lot of people.

**Comment by AndrewArch** [comment]
EO 18/2
suggested to leave open as now shortened (rather than reveal/hide) as legal implications
also consider consistency across all disclaimers in site-redesign

**Comment by maryjom** [comment]
We have made the text shorter and in a collapsible section, that is defaulted to open. There isn't any current capability to remember the open/collapsed status.  ...And Andrew has suggested we eliminate the collapsible functionality.  

Is it possible to get agreement on this so we can close the issue or know if there's something more to change from the current prototype?

**Comment by iamjolly** [comment]
@maryjom - Does this need discussion/decision from the group? If not, I can remove the collapse/expand functionality entirely. We can always add it back if needed.

**Comment by iamjolly** [comment]
Well, by pulling the Disclaimer into the Introduction section in issue #13, the collapsible functionality was removed. Per my previous comment, this can be added in, if needed.

**Comment by maryjom** [comment]
I don't think so. The suggestion being made was to collapse the multiple
sections into a single section which is now significantly smaller than it
was before.  So I think we can remove the collapse as the information isn't
all that intrusive any more.


Best regards,


Mary Jo
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                    Mary Jo                                                                    
                    Mueller                                                                    
                    Accessibility                                                              
                    Standards                                                                  
                    Program                                                                    
                    Manager                                                                    
                    IBM                                                                        
                    Accessibility,                                                             
                    IBM Research,                                                              
                    Austin, TX                                                                 
                    Phone:                                                                     
                    512-286-9698 |                                                             
                    Tie-line:                                                                  
                    363-9698                                                                   
                    Search for                                                                 
                    accessibility                                                              
                    answers                                                                    
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               
                                                                                               



"If your actions inspire others to dream more, learn more, do more and
become more, you are a leader."
~John Quincy Adams



From:	Robert Jolly <notifications@github.com>
To:	w3c/wai-policies-prototype
            <wai-policies-prototype@noreply.github.com>
Cc:	Mary Jo Mueller/Austin/IBM@IBMUS, Mention
            <mention@noreply.github.com>
Date:	03/30/2017 10:33 PM
Subject:	Re: [w3c/wai-policies-prototype] Disclaimer (#1)



@maryjom - Does this need discussion/decision from the group? If not, I can
remove the collapse/expand functionality entirely. We can always add it
back if needed.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by slhenry** [comment]
+1 for not having collapse. (and closing this issue for now and people can re-open if wanted)
