### ISSUE TITLE
level of detail to include

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#10]
@maryjom : Only add relevant links to the text of the law, legislation and/or rule(s)/standard(s) that provide the basis and specific guidance for complying with the web accessibility regulation.

@maryjom : I would prefer not to have an additional information part. We could potentially have the following additional  information per country, though these aren’t just Web accessibility related:
 Digital accessibility strategy for the country

**Comment by yatil** [comment]
I wonder if “Digital accessibility strategy for the country” is easily determined and can be captured in this document. We don’t want to interpret what countries are doing.

**Comment by bakkenb** [comment]
Would like to see the [prototype](https://w3c.github.io/wai-policies-prototype/) updated with the level of detail in the countries that was put in the Word document proposal. This will help me react to the level of detail that is on the page. So far I am okay with the level of detail displayed in the Word doc proposal by Mary Jo. (I don't do a lot of work where I need to look up country policies, so I am relying on others for this feedback.

**Comment by iamjolly** [comment]
@bakkenb :: I can work on getting the prototype updated with all of the data from the Word document this week (before our call on Friday) so that the page will be more reflective of the full contents.

**Comment by bakkenb** [comment]
Thanks @iamjolly! Really appreciate that.

**Comment by yatil** [comment]
Hi @bakkenb & @iamjolly – I think I have included all fields that are in the word document… have I missed some? (You can expand the different laws.)

If you want different entries (for different countries), I think Robert can easily do that. :-)

**Comment by slhenry** [comment]
Agree that we want to limit the amount of additional info we include. However, there may be some cases where that is extremely helpful -- e.g., an agency/ministry provides a supporting doc that really clarifies a complicatedly-worded regulation.

Note that we want to include only "official" documents, and not include unofficial commentaries and interpretations. We will need to say this in the submission form.

**Comment by iamjolly** [comment]
@AndrewArch @yatil @bakken @slhenry @maryjom  - I have added Canada, China, and European Union (for now) and I'm sure there are some typos and changes that will need to be made in future updates. This should start to show the table growing as well as offer a glimpse at the page's overall content length. It will be bigger once all of the info from the proposal document is added.

**Comment by maryjom** [comment]
All of the countries from the Word prototype are now in the live one.  We are still missing some countries that were in the original policies page, and I will continue to work to add the appropriate/updated information for countries where the links are working and not broken. Otherwise I'll leave it to content submitters using the submission form we create to update it.
