### ISSUE TITLE
Confusing navigation pattern for collapsible details on laws/legislations

### ISSUE THREAD

**Issue by dboudreau** [w3c/wai-policies-prototype#11]
I think it's very confusing to rely on the small right-pointing arrow to indicate the presence of additional details for any given law/legislation under a country. The country itself has a regular bullet which is not clickable, yet the links underneath have what seems to be bullets (the arrows), but those are clickable to expand the section. When one clicks or triggers the links themselves however, it leads to the URL of said law/legislation. I think we should change the visual presentation of the call to action from a right-pointing arrow to something more obvious/predictable, like a plus sign or something.

**Comment by yatil** [comment]
This is a prototype, we use the standard HTML5 details element for prototyping reasons. We don’t know how disclosures look in the new design, so we didn’t implement that. Please don’t comment on UI yet :-)
