### ISSUE TITLE
Form: Would like to have separate link name, URL, and description fields for standards and relevant documents

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#116]
In my original design for the form I showed providing the three fields - policy name, it's URL link, and an optional description with a button that would add another group of those three fields for adding a additional standards and also when adding relevant documents.  It seems a bit confusing to provide three parts of information in a single entry field and having to provide any additional as another line in the entry field.  

Hopefully this is easy to do.  Otherwise, it may be an enhancement after the MVP version of the form.

**Comment by yatil** [comment]
Done! :-)
