### ISSUE TITLE
Submission form styling

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-policies-prototype#125]
Improve styling and layout on the form to ensure clarity/usability of the labels, fields, and the description text. 

Make label placement more consistent (some are over their fields, some are to the left).

**Comment by maryjom** [comment]
- Change "I don't know" response to "Unsure" or "Not sure"
- Add "Unsure" response to "Scope" and "Technologies" 
- Make sure sizes of entry fields change to match the size of the information we expect to get in the field.
- Instructions for fields in italics
- Add white space between fields.

**Comment by yatil** [comment]
@maryjom 

> Make sure sizes of entry fields change to match the size of the information we expect to get in the field.

Please specify what size what input field should have.

> Instructions for fields in italics

We usually don’t use italics for readability reasons.

> Add white space between fields.

Where should be how much white space?

**Comment by maryjom** [comment]
Size of fields: 
- all URL/URI entry fields, Policy Name, Standards used by policy (all 3 fields), and relevant documents (all 3 fields) should be the full available width, as some URLs, names and descriptions are quite long
- The rest of the fields maybe make them 1/2 the width of the available space so they all have a consistent look.

Instructions: OK if we aren't supposed to use italics, but want some visual difference that you can tell this isn't really a label, but are instructions.  Maybe the color of the font to be lighter, or a different font.

White space: I don't know how the space would be measured, but enough that there's about 1/2 a text line height between the bottom of the field above's entry field (or instructions if there are any) and the next field.  We can see what that looks like and adjust from there.

**Comment by yatil** [comment]
Thanks @maryjom, I’ll take care of it!

**Comment by maryjom** [comment]
Looking MUCH better!  A few minor tweaks:
- Enacted date can be a half-size entry field.
- Strange that the Responsible Entities, Standards used by policy and Relevant documents show the bullet above the text of the first field. Should be on the same line.  
- In addition, alignment of the left edge of the input fields that are in these bulleted groups are not aligned with the left edge of other entry fields that are not in a bulleted list.  This isn't a major deal, so if it's too much trouble you can ignore it.
- Another really small thing, something we can put off if it's too much trouble is that it seems that the Select WCAG version checkbox labels have a wider distance from the checkbox icon than other checkbox and radio button lists. I actually like the extra space in there, but we need to make sure it's consistent in all groups.

**Comment by iamjolly** [comment]
Thanks for taking on the styling of this @yatil. I'll pile on with a couple of related comments on this:

- Can we remove the bullet for Entities, Standards, and Documents using `ul.multiple {list-style-type: none;}`?
- The input fields seem to be pretty far from most labels. Any way to bring them closer in proximity? Not the most pressing issue, but could be appreciated by folks using high magnification.

**Comment by yatil** [comment]
> Enacted date can be a half-size entry field.

Done!

* @maryjom:
  > Strange that the Responsible Entities, Standards used by policy and Relevant documents show the bullet above the text of the first field. Should be on the same line.
* @iamjolly:
  > Can we remove the bullet for Entities, Standards, and Documents using `ul.multiple {list-style-type: none;}`?

I find the bullet to be good for orientation, but if they make problems in some browsers (they look ok for me…), consider them gone!

> In addition, alignment of the left edge of the input fields that are in these bulleted groups are not aligned with the left edge of other entry fields that are not in a bulleted list. This isn't a major deal, so if it's too much trouble you can ignore it.

Impossible to do without subgrids in CSS (the width of the containers is different therefore the percentage is different, too.)

> Another really small thing, something we can put off if it's too much trouble is that it seems that the Select WCAG version checkbox labels have a wider distance from the checkbox icon than other checkbox and radio button lists. I actually like the extra space in there, but we need to make sure it's consistent in all groups.

Added the space.

> The input fields seem to be pretty far from most labels. Any way to bring them closer in proximity? Not the most pressing issue, but could be appreciated by folks using high magnification.

We can’t have consistent field widths and close to the labels. We already have labels that are too small. What we can do is have ragged-left form inputs, like in this image:

https://dsc.cloud/yatil/Screen-Shot-2017-05-02-19-58-26/Screen-Shot-2017-05-02-19-58-26.png

**Comment by iamjolly** [comment]
I like those ragged-left form inputs @yatil. I defer to @maryjom on the final decision on those

**Comment by yatil** [comment]
FWIW I quite like them :-) (And I can have shorter for the enactdate, I just didn’t think about that when doing the quick mockup.)

**Comment by maryjom** [comment]
Typically I like labels above form entry fields for that reason - everything aligns nicely. But since this is a long form, I think that styling makes the form too long. So, ragged-left will have to stay.  Just make sure there is a little space between the label and the field. To my recollection, they were really tight together before.

**Comment by yatil** [comment]
Updated! (4c692db5f3a8b2bd0ae8243b1e17167371cfe210)

**Comment by iamjolly** [comment]
This is looking much better thanks to @yatil's efforts. Are any additional styling or content changes needed at this point @maryjom?

**Comment by maryjom** [comment]
Looks good to me. Closing.
