### ISSUE TITLE
Form submission results page needs to be updated

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#132]
Form submission results page has a lot of html or other stuff at the top that either shouldn't be there or needs formatting or suppressing.  

The issue number isn't pulled into the text of the link referring to the issue and doesn't go to the issue. Either fix or remove.

**Comment by yatil** [comment]
Yes, debugging code was on top. I did expect that I get a nod by the systeam if they fixed the issue. But I wasn’t aware that it was already “online”. Fixed the issue.

(I’ll open a new one for adding the template and make it look WAI-like.)
