### ISSUE TITLE
Filters using "and" logic rather than "or" logic

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#139]
To explain, in the filters when I select "Law" I get 1 policy that matches.  When I select "Mandatory policy" I get 1 policy that matches.  When I select both "Law" and "Mandatory policy" I get zero matching policies where I expected to see two.

This brings to mind that we may need to have some explanation or choice of using "or" or "and".  If we choose only one way, I'd like to have it be "or".

**Comment by yatil** [comment]
We usually have “or” inside a group and “and” between groups. So you could have “Show policies based on WCAG 2.0 or WCAG 2.0 derivates and in effect”

**Comment by maryjom** [comment]
That makes sense.  So the bug is that it's using "and" inside the group.

**Comment by iamjolly** [comment]
I am not sure how to address this issue, as there is no apparent property or method to set the [faceted search script](https://github.com/w3c/wai-policies-prototype/blob/gh-pages/js/facetedsearch.js) to use OR vs AND logic. I will keep digging on this one, though, and hopefully we'll have a solution to this soon.

**Comment by yatil** [comment]
Ah, was that something the faceted search can’t do? I’ll have a look!

**Comment by yatil** [comment]
So, the faceted search does that by default, but we decided to remove that functionality because people thought it was complicated to understand:

https://eikes.github.io/facetedsearch/

When you click on an item in the first column (no keyboard input), you get a (+) to add other terms from that group. I wonder if this is a must have feature.

Discuss.

**Comment by maryjom** [comment]
@yatil Yes, that faceted search works as I would expect. Each time you click another item in the same filter category it adds items that match to the results. It doesn't look for a combination of all of them to yield fewer results.

**Comment by yatil** [comment]
This now works! (7e22ece4c880d8035a2d68a88b29493baface0a6)
