### ISSUE TITLE
Terminology in the way

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-policies-prototype#14]
I suggest putting the Terminology section at the end of the document (and possibly link to it from the top if needed), *or* make it collapsible. People probably do not want/need to read it every time.

**Comment by bakkenb** [comment]
Agree that it works better on the bottom. Could it be linked too like we do in the W3C Understandings documents? [Example](https://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-av-only-alt.html) 
Or will that seem like more links to other resources rather than an anchor to the glossary/terminology?

**Comment by slhenry** [comment]
This is a *huge* page so at the bottom will be hard to find. Maybe a sidebar &/or collapsible.

**Comment by yatil** [comment]
I think this could even go on a separate “Help” page (or collapsible). It is information that you probably only need to read once or refer back occasionally. 

However it would be good if we could boil the terminology down so that it can be easily understood, while at the same time not misrepresenting the legalese.

**Comment by AndrewArch** [comment]
Definitely something that doesn't want to be read every time (if at all by some). I like the idea of 'help' or 'using this page' or similar that talks about the structure too - and maybe as a separate page?

**Comment by slhenry** [comment]
I like the idea of putting things together, but prefer collapsible &/or side bar, rather than separate sub-page. (Like on WCAG-EM Report Tool) I don't think there will be enough info for a separate page.

**Comment by dboudreau** [comment]
I'd rather have multiple pages (one per country) and no collapsible parts in the main index page, if we can. That would make the page much easier to go through, without requiring any fancy mechanisms. We did that for the Perspectives videos for example and it works really well. Also, it provides a unique URI for each country, which could also be useful...

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item09)

**Comment by yatil** [comment]
@dboudreau Basically we already have pages: https://w3c.github.io/wai-policies-prototype/policy/australia/ – We just don’t put something out there. I agree that it makes sense to have individual pages. The main page will be long enough anyway.

**Comment by AndrewArch** [comment]
also relates to #2, #3 and #4

**Comment by iamjolly** [comment]
Recommendation to move Terms to bottom of page and have a link to it in the Introduction area near the top of the page.

**Comment by slhenry** [comment]
From https://github.com/w3c/wai-policies-prototype/issues/19#issuecomment-288404406

> As I was focusing on the filter options, I was wondering what some of the words meant, and wondering if we wanted to include the description there. "Terms on this page" is above it.
>* What about putting the descriptions of the Terms in the Filter area and make it visible by default (and probably optionally collapsible). I think that would improve usability and take up less space! :-)

What I mean is in the Filter area:
[_] Term - description
[_] Term - description
[_] Term - description

**Comment by slhenry** [comment]
reminder to @iamjolly  about suggestion above :-)

**Comment by iamjolly** [comment]
Added Terms back into the Introduction area and made it collapsible (but open by default). This addresses @slhenry's [comment on Mar 31](https://github.com/w3c/wai-policies-prototype/issues/14#issuecomment-290767284). Closing for now but we can re-open this if/when needed.
