### ISSUE TITLE
Sorting of table by country isn't working properly

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#148]
When I initially bring up the page, the table isn't sorted by country any more. When I apply a filter and then try to sort the table by country, it doesn't do the alphabetic sorting correctly.

**Comment by yatil** [comment]
> When I initially bring up the page, the table isn't sorted by country any more.

I have fixed that!

> When I apply a filter and then try to sort the table by country, it doesn't do the alphabetic sorting correctly.

This works for me. Can you confirm? Maybe I am sorting the wrong thing, a screenshot would be helpful to find the problem :-)

**Comment by maryjom** [comment]
This seems to be working as expected now. Not sure what changed, but I'm unable to recreate the problem at this point.

**Comment by iamjolly** [comment]
Thank you @yatil and @maryjom! Closing for now.
