### ISSUE TITLE
better differentiate in-page vs external links

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-policies-prototype#15]
In the table it is not immediately clear what links down within the page and what takes you to another page.

**Comment by bakkenb** [comment]
Eric, will this be handled with the future stylizing and functionality development? Could anchor links be styled so that the difference is evident?

**Comment by yatil** [comment]
Yes. This is a prototype. We always mark external links and that style will also be used with this page.

**Comment by iamjolly** [comment]
@yatil - Do we have a style for external links in wai-main.css? If we have it, I'll add it. I'm combing through the styles and not finding one in there.

**Comment by yatil** [comment]
@iamjolly Use `<img src="//www.w3.org/Icons/tr.png" alt="External">` for this layout & CSS.

**Comment by yatil** [comment]
I have just added external links icons. 962da365dc03062e1bee179098578f16d09b7a5f
