### ISSUE TITLE
heading with expand/collapse and external link

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-policies-prototype#16]
I wanted to expand the section and noticed that the heading was a link, so i clicked it - but instead of expanding the section it took me to a different page. Not sure how to address that - either clearer expand/collapse toggles and link or a different approach altogether?

**Comment by yatil** [comment]
This is a known problem in this prototype. This prototype is for prototyping only. The final expand/collapse will work differently. I’m never the less separating the link from the title to make it easier to click.
