### ISSUE TITLE
Multiple languages for ministry name & related documents

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#173]
Not sure If I should keep this in or not, but I found ministry names in different languages, but the code isn't handling the language tags correctly.  See [Finland](https://w3c.github.io/wai-policies-prototype/policy/finland/) and [Denmark](https://w3c.github.io/wai-policies-prototype/policy/denmark/), for example.  In the MVP I could remove the other languages for the ministries. Just wanted to pass this by you to see if we should allow it.

**Comment by iamjolly** [comment]
We currently don't loop through languages of Ministries links like we do for country names and policy titles. But, it's possible!

Do you want us to add this bit of functionality before the MVP launch @maryjom?

**Comment by maryjom** [comment]
@iamjolly Maybe I was just overthinking it and added too much multilingual stuff in there. I don't think it's an absolute necessity, so you can move it to the post-launch and maybe we can ask our international folks attending AccessU what they think is helpful to see.  The page for the ministry links are in the native language for those countries.

**Comment by iamjolly** [comment]
That sounds like a good plan. Moving this to post-launch and hopefully we can get some feedback from folks on this at the conference.

**Comment by maryjom** [comment]
@iamjolly Found the same issue exists with related documents. I can't put the related document name in another language and have the markup work. I don't think it was enabled that way.

**Comment by yatil** [comment]
I think it is useful for related documents, but not too much for ministries.

What shall we do if a related document has no English name? (Probably moving to post-launch is OK for this tbh.)

**Comment by maryjom** [comment]
To me, ask for a translation of the name. I thought you had implemented these things in the prototype, as they are showing up with multiple languages already.  But if more work is needed, I'm OK with moving it to post-launch, as long as Shawn agrees.  She was the one that was most concerned with these multi-language things and using an English name link that goes to a different language website.

**Comment by yatil** [comment]
Yes, this was implemented, @maryjom, sorry for the confusion. I even think it’s ok with Ministries now.
