### ISSUE TITLE
Add the language to the title of a link to indicate what language the page is

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#178]
Important usability issue.

Via @slhenry.

**Comment by slhenry** [comment]
Actually, I think we just link the title in that language, then don't need additional language indication - per https://github.com/w3c/wai-policies-prototype/issues/35#issuecomment-300509696

**Comment by slhenry** [comment]
Actually, I think we just link the title in that language, then don't need additional language indication - per https://github.com/w3c/wai-policies-prototype/issues/35#issuecomment-300509696

**Comment by yatil** [comment]
I’ll make sure to implement a way to have all six ways of displaying the language as shown in #35 and this document: https://www.w3.org/WAI/Policy/updates.html#formats

**Comment by yatil** [comment]
Implemented in c8de6ab1bfd11a1f05a059a857607c34c12ccc66, fcef10d0d567569d0d34630d7c7a6374ae2bb7c5, 487e02371af935d3d164391f55dd0101d1f140f0, and fbea929507a0d995aa361a015d90e300eebaf42b.

**Comment by slhenry** [comment]
Oh, dear, I'm afraid that we had a misunderstanding :-(((

> Actually, I think we just link the title in that language, then don't need additional language indication

**Comment by yatil** [comment]
So, do we want to keep the language indicator or not?

I understand that this might not be _needed_, but it might be helpful.

**Comment by slhenry** [comment]
Note: another option is to put it at the end of the link instead of the beginning.

I've added to [feedback questions](https://www.w3.org/WAI/EO/wiki/EOWG_F2F_May_2017#Things_to_check_on:). Let's leave as is for now and revisit at the F2F, hopefully after getting some user feedback (albeit from limited perspectives)

**Comment by yatil** [comment]
I think we did not get a lot of feedback – if any – during AccessU. I’ll move the language indicator to the end of the link, we will also have the different languages as a list, from AccessU feedback in #222.
