### ISSUE TITLE
Button for Submitting new entries

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#18]
From @nitedog in #12:

> 2. We should have a button/link to an input form for updates, like we have on the [tools list](https://www.w3.org/WAI/ER/tools/). Maybe also here have an additional link for every item that would pre-fill the form for easier updating

**Comment by yatil** [comment]
Yes, we certainly need this somewhere on the page. I have not put a lot of thought into how policies would be submitted. If we stay with the technology of the prototype – and it looks like that – we might want to look into a form -> submit -> Github Pull Request workflow using the Github API. I’ll put that on my list to research.

**Comment by AndrewArch** [comment]
@yatil that approach sounds neat :)

**Comment by nitedog** [comment]
Is there anyway to reuse an existing system that we already have, like the tools list or the components list? Creating and maintaining yet another system seems superfluous. Ideally all three would eventually end up using the same approach to reduce maintenance overhead.

**Comment by yatil** [comment]
@nitedog I’m happy to talk about the problems I see with the approach of the Tools list (mainly related to vetting). When we figure this out (should be _relatively_ simple*) we can retroactively use it for the Tools list as well, as they use almost the same approaches.

*Yes, there I said it. When will I ever learn ;-)

**Comment by nitedog** [comment]
I'm curious to hear more about your new approach when you do the research - hope it could be useful for the components list too?

**Comment by yatil** [comment]
@nitedog As the components list uses WordPress, it is unlikely. However that might change if my masterplan works out… (I suggest discussing this separately :-D)

**Comment by iamjolly** [comment]
@yatil - I don't know if you've looked into this much yet. I just found an interesting article and related service talking about a similar sounding approach.

Article: https://nourish.je/my-new-comments-system/
and
Service: https://staticman.net/

**Comment by yatil** [comment]
@iamjolly Yes, the new comments system article is probably how to do it, with an HTML form that does the heavy lifting for us. Maybe we generate the code via the form and then send it in as a pull request or issue (the latter is probably easier at first) for review.

**Comment by yatil** [comment]
We have implemented this.
