### ISSUE TITLE
Sidebar only Country listing [medium]

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#183]
I think the sidebar should be only "Country Details" with list of countries.

* "Contents" as an overall heading is potentially confusing since most of the links go off page.
* I don't think these aren't needed in the sidebar:
"Introduction
Law & Policy by Country — Overview Table"

**Comment by slhenry** [comment]
I think this should be done before launch.

**Comment by slhenry** [comment]
This looks good! We can close it, yes?

**Comment by iamjolly** [comment]
Yes!
