### ISSUE TITLE
Filter collapsible? [mild]

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#184]
I noted Adina saying the page was very complicated. And that we already have Terms collapsible.

Perhaps we also want to make the "Filter policies to show:" section collapsible -- to allow simplification of the visual...

**Comment by iamjolly** [comment]
Agree it could be useful to make it collapsible, but not urgent priority. This is something we can ask for feedback on during AccessU and from outside people, then implement. 

FWIW, if the filters are made collapsible, I do not think the filters should be closed/collapsed by default. That is also something we can usability test against, too.

**Comment by slhenry** [comment]
agree they should be open by default (as the terms are)
