### ISSUE TITLE
Update submission form for multi-language input

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#189]
This still needs to be done by me.

Rel. #178.

**Comment by maryjom** [comment]
@yatil Is this issue handled with the code from #177 or is there something additional to do here?

**Comment by iamjolly** [comment]
I think this is something else to be done here, but it is **not** a launch-stopping issue IMO. 
My understanding is that there will be a way to specify the language of links/resources added to the form itself. 

Moving to Post-Launch milestone for the remaining work on this one.

**Comment by yatil** [comment]
This is still open, I try to work on it in the next few days – totally not a shop stopper :-)

**Comment by yatil** [comment]
Done!
