### ISSUE TITLE
Add or Update Listing more findable

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#190]
Norah in [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-5-May-2017/results#xq2):
> Also, I think the Add or Update Listings / Submit an Update option could be
easily overlooked where it is located under the left navigation Contents
listing. At a glance, the section looks more like summary or descriptive
information rather than an invitation to the user to submit or update a
policy (even though it is clearly labeled, I think it could be overlooked
in that location beneath the contents.)

+1

I had [suggested we include it in the Introduction](https://github.com/w3c/wai-policies-prototype/issues/13#issuecomment-295468708), and I still think that is a good idea. (can also leave it in the sidebar)

**Comment by iamjolly** [comment]
This is something worth discussing on Friday's call. I don't mind it being in either place, but it doesn't make sense to have it in both the intro and the left column, especially considering all of the concerns that have been raised regarding simplifying the user interface.

**Comment by dboudreau** [comment]
I lean towards keeping it in the left column under the countries box, but if we feel like it also needs to be a part of the introduction, then I can live with that, too.

**Comment by slhenry** [comment]
Discussed in 12 May teleconference. Agreed to leave sidebar, and add simple sentence (no button) in intro.

**Comment by maryjom** [comment]
I also added a sentence in the intro about the ability to submit updates.

**Comment by iamjolly** [comment]
Hi @maryjom --- there was already a sentence added in the first paragraph with a link. Do you want to consolidate these two into one? I think it's needed now.

**Comment by maryjom** [comment]
Didn't realize that. Ok we should consolidate it.  You want to do it or me?

**Comment by iamjolly** [comment]
No worries. If you can tackle that, I would be most grateful! :)
