### ISSUE TITLE
Do we need breadcrumb?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#197]
Seems to be redundant with the navigation…

**Comment by iamjolly** [comment]
Related to #183. 

On country pages, we need either the breadcrumb or side navigation to return to the main page with the summary table. 

Thoughts, @slhenry or others?

**Comment by yatil** [comment]
We have the side navigation, maybe we can word the link to home more clearly and avoid the repetition of the breadcrumb.

**Comment by slhenry** [comment]
Yes, please add a breadcrumb overall. (That might change with site redesign later).

On WAI pages that don't have the WAI nav on the left, we include a breadcrumb,

Here's the [example breadcrumb](https://www.w3.org/WAI/EO/Drafts/template-no-nav)

**Comment by yatil** [comment]
@slhenry What would be the complete path to the overview pages?

**Comment by slhenry** [comment]
Site Navigation: W3C Home > WAI Home > [Planning and Implementing Web Accessibility](https://www.w3.org/WAI/managing)

**Comment by slhenry** [comment]
looks  like breadcrumb is missing > Planning and Implementing Web Accessibility

**Comment by iamjolly** [comment]
Added missing crumb and closing! Hansel and Gretel will return home safely. :)

**Comment by slhenry** [comment]
thanks for the chuckle!!!

**Comment by slhenry** [comment]
breadcrumb should be far left, in the nav area - note from [above](https://github.com/w3c/wai-policies-prototype/issues/197#issuecomment-300780987):

> Here's the [example breadcrumb](https://www.w3.org/WAI/EO/Drafts/template-no-nav)

:-)

Don't need to hold up first publication for it, though.

**Comment by yatil** [comment]
Modified the breadcrumb exactly after the example.
