### ISSUE TITLE
feedback box

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#199]
Add the standard feedback box to the bottom WITH EDITS to include the "Submit an Update" button/link AND clarification that listing info should go there, and comments on the UI, etc. can go to GitHub (or email)

**Comment by iamjolly** [comment]
@slhenry - Is this for the submission form (add/update a policy form page) or is this a footer change across all pages?

**Comment by yatil** [comment]
It’s this box: https://www.w3.org/WAI/gettingstarted/tips/index

**Comment by iamjolly** [comment]
Thank you @yatil - that makes sense
