### ISSUE TITLE
Law vs Legislation

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#2]
@maryjom said: Comment received that these are used interchangeably in countries outside of the U.S. Not sure if that is because people don't understand the difference or if there really is no difference in the definition in other countries.

> Law – Law that has completed the legislation process, and goes into effect as the law of the land.  
Legislation – A law that is in the process of becoming a law, commonly referred to as proposed legislation.

**Comment by AndrewArch** [comment]
This is the case in Australia – same thing. 

Also, from [Wikipedia](https://en.wikipedia.org/wiki/Legislation)) 
> Legislation  (or "statutory law") is law which has been promulgated (or "enacted") by a legislature or other governing body or the process of making it.

**Comment by bakkenb** [comment]
Whether they are truly have different meanings or not (seems like it depends on the county), I think people use them interchangeably. Can WE use them interchangeably? That may determine the usage.

**Comment by slhenry** [comment]
@brewerj - thoughts on above?

**Comment by yatil** [comment]
We should probably be explicit and say “Law” and “Proposed Legislation” (for me “Proposed Law” would also be OK – but I am not a lawyer), as well as “Policy” and “Proposed Policy”.

**Comment by maryjom** [comment]
Closing this issue as the definitions have been updated.  If anyone doesn't agree with the definition, either reopen this and provide a comment, or open a new issue.
