### ISSUE TITLE
Wording for left menu item - Law & Policy Overview Table - not clear

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-policies-prototype#20]
I suggest changing the wording of "Law & Policy Overview Table" to "Law & Policy by Country - table" and the menu item below that one: "Laws & Policies by Country" to "Laws & Policies by Country - detail." 

I expected to find the table when I went to the latter and jumped right past the table. Someone not familiar with this page might miss the table altogether.

**Comment by AndrewArch** [comment]
thanks @hkramer - that makes sense to me :)

**Comment by iamjolly** [comment]
If we use something other than a table to filter/sort the contents of the page, this may change altogether. But, for now, the clarification is good to have. Will update the prototype but keep this issue open for further discussion.

**Comment by maryjom** [comment]
This has been done in the prototype.
