### ISSUE TITLE
[minor - low priority] spacing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#200]
Less space after "Terms used on this page" heading and the list underneath it.

**Comment by iamjolly** [comment]
@slhenry - How does this look now (pushed an update)?
![screenshot 2017-05-11 10 24 18](https://cloud.githubusercontent.com/assets/1093423/25960425/20cbd946-3634-11e7-990c-54e0d0f0176a.png)

**Comment by slhenry** [comment]
nice!
