### ISSUE TITLE
When policies page goes live: be sure links from other EOWG/WAI to point to it

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#201]
Don't know how many pages link to the policies page, but they'll need to be updated to point to the new page I think, unless you copy over to a file with the same name as the old one.

They'll also need updated link text for the new title.

Here's one page I found that has a link: https://www.w3.org/WAI/managing

**Comment by slhenry** [comment]
I'm planning to put it at the same URI as the previous version.

We'll need to update the title in https://www.w3.org/WAI/managing is the main page, also the nav, and a few other pages -- although that might not be high priority to do before/with launch.

**Comment by maryjom** [comment]
Yes, but with change in title the link text will be incorrect.

**Comment by slhenry** [comment]
I'll update the pages. Eric - would you update the navigation?

**Comment by yatil** [comment]
Sure, @slhenry!

**Comment by slhenry** [comment]
Eric - please move it to the top of the list under "Policy Resources". ping me if questions. thanks!

**Comment by yatil** [comment]
I think this has been addressed.
