### ISSUE TITLE
Provide definitions for the options under "Type of Policy"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-policies-prototype#204]
Rebecca's feedback (1 of 2):

> One initial thought on the form is to consider definitions for the "type of policy" options (all the other fields seem straight-forward). In some recent international survey work, I've run into problems with interpretation of key terms, even between speakers of the same language, given differences in government and cultural contexts. Providing definitions may help.
> 
> Also, you may wish to double check that you are clearly able to separate laws from regulations (which I suppose depends on the country's system of government). If it's a regulation, you may want to know what government agency issued the regulation.

I received this feedback about the Web Accessibility Policy submission form from Rebecca Sheffield --
 https://www.linkedin.com/in/rebeccasheffieldphd/

Rebecca's last sentence suggests an additional functional enhancement, to ask the submitter to identify the agency that issued a regulation. However, we can address this concern to some extent through definitions of terms. The definitions should encourage submitters to identify the issuing agency through the "Relevant documents" fieldset and/or the "Notes or comments". If we later see enough interest, it could become a distinct field in the future.

**Comment by yatil** [comment]
Hi @mitchellevan, thanks for the testing. I’ll make sure we have the definitions in the form. The issuing government agency would be captured in the “responsible entities” field, so I think we’re ok on that front.

**Comment by maryjom** [comment]
@yatil I'm not sure how to code this properly. Would the definition be part of the label, or an additional ARIA type of label that the checkbox would be aria-describedby?  If I provide the definitions, could you code it up as you see best?

Accessibility law - A general accessibility law that has a broad scope of non-descrimination, accessible technology, employment and/or other topics. 
Non-discrimination law - A law intended to prevent unfair treatment of persons with disabilities.
Procurement law - A law that requires government purchase of accessible goods and services.
Procurement recommendation - An optional, but encouraged goal to purchase accessible goods and services.
Mandatory policy - Required accessibility goals or implementation that is not regulated by law.
Recommended policy - Optional, but encouraged accessibility goals or implementation that is not regulated by law.
