### ISSUE TITLE
dates for entries

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#21]
which dates should we include for an entry?

Seems important to have:
- when the law/policy was approved
- when the law/policy went into effect
- any other date-based info? (eg sunset date if exists?)

We may not be able to provide all dates for all laws/policies, but we should aim to provide when we can.

**Comment by slhenry** [comment]
+1

**Comment by yatil** [comment]
I think we should probably keep it simple: future law, current law and outgoing law, it would be good to do that with dates it would be need, but it is less useful if it is not reliable – We certainly should mark where we have good data and where we don’t have it.

**Comment by yatil** [comment]
From the February 28th F2F: 
* Enacted date would help with simplifying the table, the updated date would be useful. Maybe just use a year as most of the policies have multiple dates.
