### ISSUE TITLE
WCAG version used filtering bug with the number of "items" vs. "add"

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#216]
If you have a WCAG version used item, and then in the Type you pick one with 0 items then the text on that (0 items) shows (add). Should stay at (0 items)

**Comment by yatil** [comment]
Does that mean that we don’t want the “add” functionality? If we want to keep the “add,” we have a label that is even easier to understand, if we keep “(0 items)”. (If anything it should probably be “(x items),” as it adds items.)

No matter what we decide, I need to deviate quite a bit from the standard code of the filter library.
