### ISSUE TITLE
Different background color for the left navigation

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#217]
As discussed in the F2F meeting in Austin on 2017-05-20.

**Comment by slhenry** [comment]
So that it is differentiated from the main WAI nav that is throughout the WAI website.

... In response to user feedback  sessions.

maybe the yellow from https://www.w3.org/WAI/users/inaccessible

**Comment by iamjolly** [comment]
This is complete. @slhenry :: I didn't use the same yellow, as it seems too bright and clashes with the overall palette of the site. Using a color that is less "bright" but still has 10.5:1 contrast ratio with text.

**Comment by yatil** [comment]
There is still blue left behind the current navigation item: https://dsc.cloud/yatil/Screen-Shot-2017-05-25-10-19-15

**Comment by iamjolly** [comment]
That was intentional but... if it seems odd or confusing I can make that the same color as the country list. I will do that and then we can see if it works well or needs more massaging.

**Comment by yatil** [comment]
Ah, I see it. I think it would be less confusing if the color of the active item was different. This way, it looks broken to me. I like having the blue on the sub-pages, only the treatment on the top-level page got me confused.

**Comment by slhenry** [comment]
Why introduce a new color to the WAI website? I thought at the f2f we talked about just making it white background. Does that work?

**Comment by yatil** [comment]
White would look broken to me. Yellow is really ugly. As this color will only be on the site for a few weeks, I vote for leave as is or revert to the blue color.

**Comment by slhenry** [comment]
/me thinks the tan is really ugly :)
/me objects to the blue 'cause it means overall WAI site nav.

can we look at draft with white to confirm it really looks broken to you? ;-)

/me thinks "a few weeks" is wildly optimistic :/ *and* we will be announcing this widely and I expect it to gets lots o' attentions before it is redesigned.

**Comment by yatil** [comment]
/me think the confusion with main site nav is not a problem because it is redundant. From my POV we could get rid of the left column altogether. It is still handy, so I’d leave it.

I just want to keep us focused and not distracted by minutiae.

**Comment by yatil** [comment]
White. Looks completely like from another universe:
https://dsc.cloud/yatil/Screen-Shot-2017-05-25-21-22-21

**Comment by slhenry** [comment]
I like it. Call me an alien. :)

**Comment by iamjolly** [comment]
White is jarring but less so than the yellow. Since the color is relatively trivial and will change with the redesign, I'm happy to go with the flow.

**Comment by slhenry** [comment]
um - I think I meant the background of the page, not actually white. :-/

That should be less jarring. Good compromise for now?

**Comment by iamjolly** [comment]
Seems like a good enough compromise for now. Thanks!
