### ISSUE TITLE
Fix Mobile View

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#227]
Has horizontal scrolling, table needs to be linearized
![img_1277](https://cloud.githubusercontent.com/assets/58862/26448134/5d93e804-4111-11e7-9b8d-f13cbd0dbf24.PNG)
![img_1278](https://cloud.githubusercontent.com/assets/58862/26448135/5da99640-4111-11e7-9aef-d1b0363d01db.PNG)
![img_1279](https://cloud.githubusercontent.com/assets/58862/26448136/5dab409e-4111-11e7-9cdc-0c60cc58622d.PNG)

**Comment by yatil** [comment]
I'll take care of this today.

**Comment by iamjolly** [comment]
Submission form needs a little love (but not much) for small screens. 
![img_5314](https://cloud.githubusercontent.com/assets/1093423/26462380/c2d5c56c-413d-11e7-81e5-9aea9ef2be09.PNG)

**Comment by yatil** [comment]
@iamjolly True!
