### ISSUE TITLE
submission form title & h2 & breadcrumb

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#229]
I think change title to: 
> Add or Update a Web Accessibility Law or Policy

I think do not need the [h2] that's there now.

Add breadcrumb.

**Comment by slhenry** [comment]
In the breadcrumb, "Web Accessibility Laws and Policies" should go to
https://www.w3.org/WAI/Policy/Overview

... at least when we launch. Unless y'all have that set to fix itself programmaticly, I suggest we go ahead and put the right URI so we don't forget to change it when we publish :)

**Comment by iamjolly** [comment]
We have the breadcrumbs pointing to the correct landing page for Policies dynamically, so we'll just want to confirm that when we launch it.
