### ISSUE TITLE
submission form - country list?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#231]
Do we want the country list on this page, or is it unnecessary complexity?

I assume we don't want the "Add or update listings" section...

**Comment by iamjolly** [comment]
I like having the countries list on the submission page for consistency, and also for jumping to a country page to see what's there (perhaps that's an edge case I'm imagining).

@slhenry - You're right that we don't want the add/update listings section. About to get that removed from the sidebar include file for that page.

**Comment by yatil** [comment]
+1 for keeping the country list. It is very empty otherwise. And it helps users to go to other pages if they are unclear on the meaning of a field…
