### ISSUE TITLE
[low, later] Help improve this page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#232]
I wonder about moving the "Help improve this page" box from the bottom to the left column?

Maybe let's wait and see how things pan out with the redesign...

**Comment by iamjolly** [comment]
> Maybe let's wait and see how things pan out with the redesign...
💯 to that! :)

**Comment by yatil** [comment]
We always have the “Help improve this page” box in the main column in the old layout.

**Comment by yatil** [comment]
I am closing this issue, let’s see for the redesign. (It should have a flexible module that can be placed where ever we want it.)
