### ISSUE TITLE
[low/later] Find out if French policy is mandatory or voluntary and mark it so

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#241]
The summary table shows the French policy as simply "policy" and it should say if it's mandatory or voluntary. This will take some investigation, but I don't think we need to hold up the publication of the page for this minor update.

**Comment by yatil** [comment]
@notabene Can you comment on this? :-) 

[@maryjom, @notabene is a new participant in EOWG from France, so that should shortcut the investigation time significantly! :-D]

[@notabene Now you see what you got yourself into! ;-)]

**Comment by notabene** [comment]
[haha @yatil 😄 ]

@maryjom I would say mandatory by default, can you be more specific as to which law so that I can elaborate?

**Comment by notabene** [comment]
Also, this pull requester person is me too:
https://github.com/w3c/wai-policies-prototype/pull/254
😉

**Comment by yatil** [comment]
@notabene I think it is about this policy: https://www.w3.org/WAI/Policy/policy/france/#order-of-29-april-2015-on-the-general-accessibility-framework-for-public-administrations

**Comment by notabene** [comment]
I checked it and it says that the French referential (RGAA 3.0) is approved, thus applicable, thus mandatory according to the French law (an “Arrêté” is like a Decree in French law).

So, yes, @maryjom mandatory would be better.
