### ISSUE TITLE
bug - position of table relative to filers

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#242]
zoomed out and table moved to right of filters

![image](https://cloud.githubusercontent.com/assets/6991814/26800600/8357c546-49ff-11e7-8559-b4242fa5430c.png)

**Comment by iamjolly** [comment]
@slhenry - I'm wondering if you can check to see if your css may be cached. Perhaps you can do a force reload/refresh and see if the problem persists. If it is still happening, will you let me know what browser and OS you're using?

Here are screenshots of Windows 10 on a 34" ultra-wide monitor using Firefox, IE 11, and Chrome. 
<img width="1713" alt="win10-chrome" src="https://cloud.githubusercontent.com/assets/1093423/26802269/1faa3382-49fd-11e7-8a90-54ddff466c4e.png">
<img width="1722" alt="win10-firefox" src="https://cloud.githubusercontent.com/assets/1093423/26802268/1fa99f26-49fd-11e7-81fa-bb23dc4303cd.png">
<img width="1721" alt="win10-ie11" src="https://cloud.githubusercontent.com/assets/1093423/26802267/1fa8f6de-49fd-11e7-85f9-275828248b3e.png">

**Comment by slhenry** [comment]
worky now
