### ISSUE TITLE
[WAI Web Accessibility Laws and Policies]

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-policies-prototype#255]
This is a comment related to the [WAI Web Accessibility Laws and Policies](//w3c.github.io/wai-policies-prototype/)

the following link is broken http://w3c.github.io/WAI/Policy/CA-Provinces.html from the above page

**Comment by iamjolly** [comment]
Thank you for catching that broken link, @a11ycob. We'll update the Canada policy page shortly with the corrected URL in the link.

**Comment by yatil** [comment]
Done!

**Comment by a11ycob** [comment]
Thanks, Eric!

Chris O’Brien
Accessibility Officer
416-818-9411
ami.ca<http://www.ami.ca/>
Facebook<https://www.facebook.com/AccessibleMediaInc> | YouTube<https://www.youtube.com/user/AccessibleMedia> | Twitter<https://twitter.com/AccessibleMedia>
[AMI: Accessible Media Inc]
