### ISSUE TITLE
[WAI Web Accessibility Laws and Policies]

### ISSUE THREAD

**Issue by goodwitch** [w3c/wai-policies-prototype#261]
This is a comment related to the [WAI Web Accessibility Laws and Policies](//w3c.github.io/wai-policies-prototype/).  I thought the "Web and Mobile Accessibility Directive" in the "European Union" only currently has the public sector in scope.  I think it does not yet include private sector.  But in the table at https://www.w3.org/WAI/Policy/ the scope is listed as "private".  So...I'm I wrong?  Or is this a typo?

**Comment by iamjolly** [comment]
Thanks for the thoughtful question, @goodwitch. 

Page 16 of the standard's PDF (English version) states: 

> The present document specifies the functional accessibility requirements applicable to ICT products and services, together with a description of the test procedures and evaluation methodology for each accessibility requirement in a form that is suitable for use in public procurement within Europe. The present document might be useful for other purposes such as procurement in the private sector.

So, you are correct that the standard is intended for public entities. However, it does apply to private entities (think Microsoft, Apple, and other companies) who sell products and services to governments and public-sector organizations. 

I don't think you're wrong, but I also don't think it's necessarily a typo to have private sector listed. :)

Sorry if the answer isn't very definitive. I'd like to keep this question open for further review with the EO group and, hopefully, determine an appropriate way to further describe scope of policies in our resource.

**Comment by goodwitch** [comment]
Ahhhhh...then I'd love to see that distinction made clearly.  Perhaps we have clear scope definitions for

- Public Sector
- Private Sector (when selling to Public Sector)
- Private Sector

Because...I worry that if we include the "selling to public sector"...then all of these laws apply to Private Sector (when doing business with the public sector).  I know that private companies really are looking for the answer to this question:

Does my private business site need to be accessible in this country for my regular customers?

g

P.S.  I heart EO!

**Comment by yatil** [comment]
IMHO we should only list who is directly affected by the regulation, in this case, the public sector. It already says that it’s a procurement regulation, so it is procurement by the public sector.

**Comment by yatil** [comment]
I’ve assigned @maryjom, @slhenry, @sharronrush and @bakkenb to see if they have an opposite opinion. :-)

**Comment by yatil** [comment]
Also summon @nitedog, because he knows everything!

**Comment by sharronrush** [comment]
Yes, I agree with @yatil . The listing should indicate public sector and a note may be made about vendors who sell to them.  Glenda's point about trying to determine in what parts of the world my private business web site must be accessible is not clear enough with the current conflation of public/private.  Thanks for your input @goodwitch. This is a newly revised resource and we are learning how to present and support it. Your input is highly valued.

**Comment by nitedog** [comment]
@goodwitch and @iamjolly I think you are both correct because you are both talking about slightly different things! ;-)

The EU Directive on Web Accessibility applies to a specific definition of public sector bodies (technically it excludes some types of websites, such as broadcasters, but then includes some NGOs and interest groups). See Article 3(1) of the *Directive*.

The other aspect is the standard EN 301 549, which the EU Directive currently uses. This standard is intended to apply to any type of ICT. It is expected to be used in several EU policies and legislation (there is another Directive for broadcasters in the works, an Accessibility Act, procurement policies, etc.).

Side note: I suggest changing the link to the Directive to http://data.europa.eu/eli/dir/2016/2102/oj

**Comment by yatil** [comment]
Thanks, @nitedog! So we should leave public and private. At least that is my impression.

**Comment by maryjom** [comment]
@goodwitch Yes, it's a typo.  So many details. Thanks for catching it and keep 'em coming.

**Comment by nitedog** [comment]
@yatil no - since this entry is about the *Directive* rather than the *standard* it currently uses, the correct scope is public.

**Comment by iamjolly** [comment]
OK. Reading through all of this helps me make sense of things. I'll issue a PR with a change to this to remove `private` from the scope. 

Thank you @goodwitch, @yatil, @nitedog, and @maryjom for both the issue and discussion.

**Comment by yatil** [comment]
Thanks, @nitedog. Good to have you! :-D

**Comment by slhenry** [comment]
/me transfers her vote to nitedog :-)
