### ISSUE TITLE
Add field for WCAG derivates comments

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#284]
Norway: “WCAG 2.0, WCAG 2.0 levels A and AA, with the exception of success criteria 1.2.3, 1.2.4 and 1.2.5.”

Currently we only say WCAG 2.0 derivate, but we might want to add a comment that does not show up in the main table.

**Comment by sharronrush** [comment]
@iamjolly please address

**Comment by iamjolly** [comment]
Per F2F meeting comments, we want to avoid using the term "derivative" and use a term like "based on". Closing issue due to that.
