### ISSUE TITLE
Other national policies?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#293]
_From @AndrewArch on August 12, 2016 12:48_

Should we consider including local industry or other (web) accessibility policies too where applicable? Eg [Australian Bankers Assoc](http://www.bankers.asn.au/Industry-Standards/ABAs-Accessibility-of-Electronic-Banking-/Industry-Standards---Accessibility)

_Copied from original issue: w3c/wai-policieslist#2_

**Comment by slhenry** [comment]
Related to https://github.com/w3c/wai-policies-prototype/issues/328

**Comment by slhenry** [comment]
EOWG Resolution: Out of scope of this resource.

Along with "Developing Org Policies" resource, wishlist of database of example policies.
