### ISSUE TITLE
What about in-progress regulations?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#296]
_From @maryjom on August 19, 2016 23:8_

Should content include in-progress regulations?  If so, should we also note the impact, how far they are in the process, how imminent the completion is?

_Copied from original issue: w3c/wai-policieslist#5_

**Comment by iamjolly** [comment]
F2F meeting notes: We will note "in progress" but we will not monitor or update the progress unless we are advised of changes (up to editors’ discretion)
