### ISSUE TITLE
Mark which policies are voluntary vs. carry a penalty.

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#297]
_From @maryjom on August 19, 2016 23:10_

Should content include whether or not this is voluntary or penalties involved (e.g. India govt. recommendation to use WCAG 2.0 that is not enforced vs. AODA with monetary penalties)?

_Copied from original issue: w3c/wai-policieslist#6_

**Comment by slhenry** [comment]
EOWG Resolution: Beyond purview of EOWG.
