### ISSUE TITLE
Useful to have sorting capabilities for comparisons to be made

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#298]
_From @maryjom on August 19, 2016 23:12_

Users would like sorting capabilities to be able to compare countries. Some possibilities are: 
1. Is it an accessibility policy, vs non-discrimination policy, vs procurement policy, etc.? 
2. Does it apply to web only or is it broader? 
3. Does it reference WCAG directly or through another mechanism (e.g. Copy &paste)? 
4. Does it use WCAG as-is, or some derivative of WCAG? 1.0 vs 2.0? How to handle generic references to WCAG or WAI?

_Copied from original issue: w3c/wai-policieslist#7_

**Comment by slhenry** [comment]
EOWG Resolution: Not provide that functionality in tool. Instead, provide downloadable (#37)
