### ISSUE TITLE
Definitions - public sector

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#3]
Some [organizations in the public sector] do [seek to generate a profit] in Australia – eg the Government owned Australia Post. In Australia we have ‘corporate’ and ‘non-corporate’ government entities as well as Commonwealth companies. Refer [PGPA Act 2013](http://www.finance.gov.au/resource-management/pgpa-act/)

@maryjom drafted:
> Public sector – Includes government and government-run or owned entities, and entities that receive government funding. Organizations in the public sector do not seek to generate a profit.

**Comment by slhenry** [comment]
I also stumbled on these distinctions. I wonder if "governmental" and "public" would work?

@brewerj & @nitedog - Thoughts?

@AndrewArch - Do you want to suggest revised categories and explanations for Public sector and Private sector? ;-)

**Comment by maryjom** [comment]
Closing this, as the updated definitions are included in the prototype.  Reopen if the definition is still unclear with suggested modifications to the text.
