### ISSUE TITLE
Notification e-mail list for updates

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#301]
_From @slhenry on October 1, 2016 18:31_

Separate list? Or part of new announcements list?

_Copied from original issue: w3c/wai-policieslist#10_

**Comment by iamjolly** [comment]
Question is: Do we need to have a separate announcement list for Policies updates?

**Comment by iadawn** [comment]
@shawna-slh I don't feel that a separate announcement list is really required? It creates an additional maintenance burden and is unlikely to be updated that much.

**Comment by shawna-slh** [comment]
well, OK. At least one person asked for it. I was hoping it could be automated. Definitely do not want additional maintenance burden!

/me debates: Possibly leave this issue open for low priority future enhancement?

and decides not :-)

Note: We do not want to use the public-wai-announce list
