### ISSUE TITLE
[Policies] Sortable table vs filters

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#304]
_From @sharronrush on January 13, 2017 18:56_

Options under consideration are:
1.  Sortable table
2.  Filters
Please discuss your preference and the reasons for them.
       

_Copied from original issue: w3c/wai-policieslist#13_

**Comment by yatil** [comment]
_From @nitedog on January 16, 2017 16:33_

Does it need to be either-or? For example, I want a list of all the countries that adopted WCAG2 in chronological (vs alphabetical) order. This would need both filtering and sorting. I think we definitely need filtering to reduce the amount of information, but it seems that sorting would be relatively easy to implement on top of filtering.

**Comment by yatil** [comment]
_From @slhenry on January 17, 2017 21:18_

My thought right now is to have both *simple* filtering and a sortable table. It would be nice if we could meet most users needs with only a few filtering options and without lots of columns in the table (and users can get more details in the full listing).

Related material: [Use Case & Usage examples](https://www.w3.org/WAI/EO/wiki/Policies_Updating#Intro).

**Comment by yatil** [comment]
_From @bakkenb on January 18, 2017 19:28_

Just my opinion (and it may actually change when the prototype or mock-up is further developed), but I like having both options. I think people will be more forgiving of a very lengthy page for this particular resource because of the nature of the content. 

The table is great because it can quickly display specific columns of important data at a glance as your scroll down the table. As a bonus, those columns can be made sortable so that the table is more useful to the individual upon sorting.

Then being able to provide VERY basic and simple filters (just a few) would make the data below the table, or the data in the table, more manageable by only displaying what they are interested in finding.

I would like to see us try to implement both sorting and filtering to start with and see how the mock-up turns out. Then the working group can react to the usability of those functions.

**Comment by yatil** [comment]
_From @susanatx on January 19, 2017 1:59_

I'm okay with both but would say filtering if we could only choose one.

**Comment by yatil** [comment]
_From @sharronrush on January 19, 2017 15:14_

Can we get an estimate of effort? Can we use any of the existing UI of tools that we are using? Seems like that would be a factor. How difficult will it be to implement a filter that is delivered within a sortable table? Is this a question for Eric?

**Comment by yatil** [comment]
@sharronrush: It depends on the filter options and how they interact with each other (and/or filtering, for example), but a simple filter is not much trouble. We already have a sortable table and we would just hide (display:none) non-matching table rows.

**Comment by slhenry** [comment]
EOWG F2F: looks addressed. 

(Can re-open  if needed.)
