### ISSUE TITLE
[Policies] Policies page update - approach and content

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#305]
_From @sharronrush on January 13, 2017 19:1_

Please comment on the mockup sent to the EOWG list and attached to this email.
 
[Policy_page_proposal_13_Jan_2016.docx](https://github.com/w3c/wai-policieslist/files/705113/Policy_page_proposal_13_Jan_2016.docx)

_Copied from original issue: w3c/wai-policieslist#14_

**Comment by yatil** [comment]
_From @nitedog on January 16, 2017 16:44_

1. I think we have too much intro text. The Disclaimer could be put into the left navigation like in the [List of Web Accessibility Evaluation Tools](https://www.w3.org/WAI/ER/tools/). If an Introduction is needed, then it could be collapsible like we did with the [How to Meet WCAG 2.0](https://www.w3.org/WAI/WCAG20/quickref/) tool.
2. I think the entries "WCAG Version Used" and "Standard used" could be combined. For example: "China Web Accessibility Standard YD1761-2008, WCAG 2.0 derivative".
3. Can we / are we planning to mostly reuse the code and design from [List of Web Accessibility Evaluation Tools](https://www.w3.org/WAI/ER/tools/)? Seems they are similar in functionality, and reusing the code and design would save us lots of maintenance effort down the road.

**Comment by yatil** [comment]
_From @lakeen on January 17, 2017 18:36_

I agree mostly with @nitedog except for 2. combining WCAG version and Standard used.  That would hinder filtering if filtering is used.

**Comment by yatil** [comment]
_From @bakkenb on January 18, 2017 20:25_

I agree with @nitedog on his first topic. I think being able to collapse some of that information by default would be good. There for those new to the resource, but hidden for those who come back over and over for the information needed.

I like the level of detail proposed under each country. I could see that it could be sometimes difficult to fit specific country information into each of those proposed categories. I have trust that Mary Jo has much experience with this data and has outlined the most plausible categories to display for all countries  to start with.

Not sure how well this will all fit into the code and design used for the Tools List resource. could work nicely and agree it would save time, but I am cautious about "forcing" it to fit into that design. Assuming that this is being considered so that filtering functionality can be utilized. I kind of like the design used with the [How to Meet WCAG 2.0](https://www.w3.org/WAI/WCAG20/quickref/) better than the Tools List design. I wonder if that could be considered?

**Comment by yatil** [comment]
_From @hkramer on January 18, 2017 21:26_

Would not combine WCAG version and Standard used. Too much info gets put into one field inhibiting quick scanning of information. 

I menu near the top linking to each country such as found at https://www.w3.org/WAI/Policy/ might be useful over the disclaimer. I'm not sure I see the Tools UI as appropriate for this tool.

**Comment by yatil** [comment]
* +1 to @nitedog’s point 1
* +1 for keeping “wcag used”. This could be an icon in the standards used columns (as it would be a filter option, not necessarily a sort option).
* @nitedog’s point 3: It might be overkill. When we know what we data we have, I guess I and @iamjolly  could code up a prototype relatively quickly.

**Comment by yatil** [comment]
_From @slhenry on January 20, 2017 14:53_

fyi,
* [feedback from @AndrewArch via e-mail](https://lists.w3.org/Archives/Public/w3c-wai-eo/2017JanMar/0015.html)
* some thorough review still pending:
** [13 Jan survey results](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-13-Jan-2017/results#xq6) includes some people who haven't gotten to review yet.
** Also, some people [missed questions in comments](https://lists.w3.org/Archives/Public/w3c-wai-eo/2017JanMar/0018.html), e.g., "[08:45] {shadi} [I didn't see the questions]"

**Comment by iamjolly** [comment]
Addressed prior to publishing the current resource at: https://www.w3.org/WAI/Policy/

If specific changes are still seen as needed to the approach and content, I recommend re-opening this issue with updated details or creating new issues for each change requested.
