### ISSUE TITLE
... Reference List

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#311]
Issue from Judy to make clear it's not what we do, just providing a list.

**Comment by yatil** [comment]
I wonder what else we would have there? I think the title “Web Accessibility Laws & Policies” is explanatory enough. Happy to change it if there are good reasons, but we just did change the name with the update, so I am hesitant.

**Comment by iamjolly** [comment]
Is this issue something that came up from confusion from someone using the resource or is it more of an internal-only concern about what _might_ be a problem @slhenry?

**Comment by slhenry** [comment]
I've asked Judy @brewerj to suggest specific wording here.

**Comment by maryjom** [comment]
@brewerj The page already says: "This page lists governmental policies related to web accessibility, although it is not a comprehensive or definitive listing."  

Is that sufficient, or what alternative wording do you propose?

**Comment by yatil** [comment]
This is now open for over a year, without a specific proposal or reasoning, so I’ll close the issue for now.
