### ISSUE TITLE
[ED] Multiple language identification?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#320]
Apologies for my lack of multi-lingual-ism.

Some listings have one language indicated, e.g., 

"(Deutsch)" on https://w3c.github.io/wai-policies-prototype/policies/germany/

Some have two, e.g.:

"(français, langue française)" on https://w3c.github.io/wai-policies-prototype/policies/france/

"(suomi, suomen kieli)" on https://w3c.github.io/wai-policies-prototype/policies/finland/

"(Nederlands, Vlaams)"   https://w3c.github.io/wai-policies-prototype/policies/netherlands/

Can you educate me (and any others who don't know) as to why?
Thanks!

**Comment by yatil** [comment]
Some languages have multiple designations for their language or different ways to say it. 

I basically took [one of the JSON files from here](https://stackoverflow.com/questions/3217492/list-of-language-codes-in-yaml-or-json) and used it, it is based (mainly?) on Wikipedia and ISO data.

Maybe @WilcoFiers can explain it for Dutch. For me it _feels_ redundant in some cases (French), but in some languages it might make a difference.

**Comment by yatil** [comment]
Wilco explained it to me via email. Basically, those second names seem to be dialects. I am confident to remove them for Dutch and other European languages, but I don’t feel confident to do it for other languages. Maybe we could send out our file to the W3C offices and they could take a look if both are needed.

**Comment by yatil** [comment]
Closing addressed with redesign/translations :-D
