### ISSUE TITLE
Add Spain

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#333]
Found this in [Chaals tweet](https://twitter.com/chaals/status/987040290224549889):

All information in Spanish:

* Spain: http://sidar.org/recur/direc/legis/espa.php
* Latin America (specifically: Argentina, Brasil, Colombia, El Salvador, Perú, Puerto Rico): http://sidar.org/recur/direc/legis/latino.php

Maybe there is some information we can gather from there.

**Comment by iamjolly** [comment]
This is good info. Thank you @yatil for passing along the information from Chaals. Consider this now in progress.

**Comment by yatil** [comment]
Surely outdated now.

**Comment by iadawn** [comment]
@daniel-montalvo Could we have a discussion on this?

**Comment by daniel-montalvo** [comment]
Hi @iadawn 

I suggest to take a look at https://olgacarreras.blogspot.com/2005/01/referencia-sobre-legislacin-espaola.html, which is more up-to-date

**Comment by iadawn** [comment]
Columbia added in [cc0be14](https://github.com/w3c/wai-policies-prototype/pull/495/commits/cc0be14d7cb4d16c40d96817eeddecac4418c97d)
