### ISSUE TITLE
Website redesign issue with the policy page table information

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#336]
When I've got a narrower view of the policy page with the website redesign, text goes beyond the boundary of the cells and overlaps text in the next column's cell.  Please find the right CSS tricks to make this work like in the previous version of the web page. Thanks!

**Comment by yatil** [comment]
(@slhenry @iamjolly for perspectives and ideas)

This is a hard problem to solve. There is `hyphens: auto` to create [automatic word breaks](https://developer.mozilla.org/de/docs/Web/CSS/hyphens) but that looks pretty unreadable:

<img width="786" alt="screen-shot-2018-05-26-10-56-41" src="https://user-images.githubusercontent.com/58862/40574507-ae75a90a-60d3-11e8-9390-ab516876eada.png">

A different idea would be to combine fields in one cell (Country, Policy name, date) but then we would lose the ability to sort the table (unless we implement a sorting ourselves that is not a table header sorting but a `<select>` with various options).

One other thing is that tables in the new design are very spacious, and especially dense tables, like the one on the policies homepage, can benefit from less padding in the cells. Some of the columns also seem unnecessary wide.

So I guess the solution might be:

- [ ] Introduce a `dense` table style with less padding in cells.
- [ ] set the width of some columns
- [ ] add hyphens to certain columns

**Comment by bakkenb** [comment]
[medium]
I lean towards your solution bullets rather than combining field data into one cell. We could be very picky about when a "dense" table style is used. But this seems to be a good case for introducing one.

**Comment by yatil** [comment]
Thanks, @bakkenb. In general, I think more airy tables are OK, but not if we have 7 columns :-D
