### ISSUE TITLE
US States, starting at Z working backwards

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-policies-prototype#341]
@iamjolly will work backward alphabetically from Z (Wyoming) to add US States to the United States entry.

**Comment by yatil** [comment]
/me leaving this todo list here :-)

- [ ] Missouri
- [ ] Montana
- [ ] Nebraska
- [ ] Nevada
- [ ] New Hampshire
- [ ] New Jersey
- [ ] New Mexico
- [ ] New York
- [ ] North Carolina
- [ ] North Dakota
- [ ] Northern Mariana Islands
- [ ] Ohio
- [ ] Oklahoma
- [ ] Oregon
- [ ] Pennsylvania
- [ ] Puerto Rico
- [ ] Rhode Island
- [ ] South Carolina
- [ ] South Dakota
- [ ] Tennessee
- [ ] Texas (Has already info)
- [ ] Utah
- [ ] Vermont
- [ ] Virgin Islands
- [ ] Virginia
- [ ] Washington (Has already info)
- [ ] West Virginia
- [ ] Wisconsin
- [ ] Wyoming

**Comment by iamjolly** [comment]
JSON file (txt, but is JSON format) containing US States’ policies and links:  
[us-states-policies.json.txt](https://github.com/w3c/wai-policies-prototype/files/2959106/us-states-policies.json.txt)

**Comment by iadawn** [comment]
Related to #342
