### ISSUE TITLE
"Laws and Policies" could need an update for EU

### ISSUE THREAD

**Issue by annethyme** [w3c/wai-policies-prototype#344]
Filing this issue after talking to Eric Eggert and @maryjom at TPAC:

On the page Laws and Policies (https://www.w3.org/WAI/policies/european-union/#web-and-mobile-accessibility-directive) the parts related to the EU could need an update, since things are evolving pretty quickly with the EU Web Accessibility Directive (WAD) entering into force this September.

*On the Web Accessibility Directive (WAD) itself:*
On https://www.w3.org/WAI/policies/european-union/#web-and-mobile-accessibility-directive it says that the WAD is an accessibility law. Technically it is a minimum harmonization directive that has to be transposed into national law by each Member State. For categorization reasons, this is awful, but it might be worth mentioning something about somewhere.

There are some resources on what a minimum harmonization directive is here:
- http://www.enhesa.com/blog/eu-directive-vs-eu-regulation-whats-difference?language=en
- https://en.wikipedia.org/wiki/Minimum_harmonisation

*For each of the EU Member States:*
Now each of the EU Member States (see countries on https://europa.eu/european-union/about-eu/countries_en) were supposed to transpose the WAD into national legislation before it entered into force on September 23, 2018.
So in theory 28 countries are ready to have their information updated on the Laws and Policies page. Plus other countries, like Norway, that are not EU members, but voluntarily adopt the WAD.

An example is Denmark, that now has "Lov om tilgængelighed af offentlige organers websteder og mobilapplikationer", https://www.retsinformation.dk/Forms/R0710.aspx?id=201794

Not all EU Member States are however this far in the transposition of the WAD.
Since all Member States can go above and beyond the minimum that is required by the WAD, these laws are essential for understanding the legal requirements for accessibility in each country implementing the WAD. E.g. Norway is looking to make WCAG 2.1 AA a requirement for both the public and the private sector.

**Comment by annethyme** [comment]
Forgot to link to my favourite EU Web Accessibility Directive go to resource: https://go.siteimprove.com/whitepaper-eu-accessibility-2017

**Comment by yatil** [comment]
> Forgot to link to my favourite EU Web Accessibility Directive go to resource: https://go.siteimprove.com/whitepaper-eu-accessibility-2017

*cough* sponsored link *cough* ;-)

**Comment by yatil** [comment]
Additional info on EU law: https://tetralogical.com/articles/public-sector-accessibility-regulations

Hope we can get this going…

**Comment by yatil** [comment]
Additional information on the EAA: https://www.a11y-act.eu
