### ISSUE TITLE
Additional Content for Web Accessibility Law & Policy page

### ISSUE THREAD

**Issue by goodwitch** [w3c/wai-policies-prototype#347]
I think there are additional countries/laws/policies that could be added to this list, based on info I'm seeing in this article.   https://sitemorse.com/news/2018/05/08/guide-digital-accessibility-legislation-around-world/

New countries/laws/policies to add include:
- Korea - Welfare of Persons with Disabilities
- Canada (Ontario) - AODA
- Canada (Quebec) - SGQRI 008
- Spain - Law 34/2002, Law 51/2003

And thank you so much for creating and maintaining this list!

**Comment by iamjolly** [comment]
Thank you @goodwitch. I've been wanting to add more info and have a few things to work through related to that (and now this). Your recommendation is both timely and helpful. Thanks again! I'll update this issue whenever these get added or if there are any questions.

**Comment by iamjolly** [comment]
EOWG F2F meeting to review: Added label for "complex" only because this amounts to four separate updates.

**Comment by iamjolly** [comment]
Assigned to @AndrewArch to split into distinct issues for content update process.

**Comment by iadawn** [comment]
@VeraLange Could you review the linked document?
