### ISSUE TITLE
Update on Japan

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#348]
via Makoto in a11ychat

> We have a national standard “JIS X 8341-3:2016” which is identical to ISO/IEC 40500:2012. So it is safe to say the national standard is the Japanese translation of WCAG 2.0, although there are appendix parts (Not normative sections).

> We also have a new law enforced in 2016. It is the same kind of law like ADA or DDA. But it has less legal obligation.

> It is called “Act for Eliminating Discrimination against Persons with Disabilities”
> See at:
> http://www.japaneselawtranslation.go.jp/law/detail/?id=3052&vm=04&re=02

**Comment by AndrewArch** [comment]
Will catch up with Makoto during CSUN to clarify

**Comment by iadawn** [comment]
@MakotoUeki I have incorporated your submissions from #374. There is one thing that doesn't quite work. The link to [JIS X 8341-3:2016](http://www.webstore.jsa.or.jp/webstore/Com/FlowControl.jsp?lang=en&bunsyoId=JIS+X+8341-3%3A2016&dantaiCd=JIS&status=1&pageNo=) itself. This doesn't seem to resolve and I can't find a suitable link to the actual standard.

Any help would be appreciated.

There is a [preview of the updated version of the entry](https://deploy-preview-496--wai-policies-prototype.netlify.app/policies/japan/).

**Comment by MakotoUeki** [comment]
@iadawn 
The law itself is here:
https://www8.cao.go.jp/shougai/suishin/law_h25-65.html

This page would also be good. It lists a bunch of links to related documents including the law itself above.
https://www8.cao.go.jp/shougai/suishin/sabekai.html
