### ISSUE TITLE
WCAG 2.1 - add data option & filter for 2.1

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-policies-prototype#349]
[From Glenda](https://lists.w3.org/Archives/Public/wai-eo-editors/2019Feb/0001.html)

**Comment by yatil** [comment]
When WCAG 2.1 is used by the data, it is automatically in the filters, so this issue will be resolved when we resolve #344

**Comment by slhenry** [comment]
WCAG 2.1 is not an option in the [submission form](https://www.w3.org/WAI/policies/submission/).

**Comment by yatil** [comment]
I added it.
