### ISSUE TITLE
Add Korea

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#353]
@goodwitch in #347 

I think there are additional countries/laws/policies that could be added to this list, based on info I'm seeing in this article.   https://sitemorse.com/news/2018/05/08/guide-digital-accessibility-legislation-around-world/

New countries/laws/policies to add include:
- Korea - Welfare of Persons with Disabilities

And thank you so much for creating and maintaining this list!

**Comment by iadawn** [comment]
Being reviewed as part of #347
