### ISSUE TITLE
Add El Salvador

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#361]
Found this in [Chaals tweet](https://twitter.com/chaals/status/987040290224549889):

All information in Spanish:

* Latin America (specifically: Argentina, Brasil, Colombia, El Salvador, Perú, Puerto Rico): http://sidar.org/recur/direc/legis/latino.php

Maybe there is some information we can gather from there.

From #333

**Comment by iadawn** [comment]
To be reviewed as part of #333
