### ISSUE TITLE
Disclaimers added to bottom of country-specific pages

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-policies-prototype#386]
1. This overall disclaimer is on the [first page](https://www.w3.org/WAI/policies/):
> The information on this page is not legal advice. If you have questions about the applicability of the policies to specific situations, please consult legal authorities for the appropriate jurisdiction.

I propose that we add it to the **bottom** of all sub-pages (that is, country-specific listing of laws and policies such as [Germany](https://www.w3.org/WAI/policies/germany/)).

2. There has been some debate about listing a link to an inaccessible page with the official law. There was a suggestion to [add disclaimer-like wording to all sub-pages](https://github.com/w3c/wai-policies-prototype/pull/379#issuecomment-585173618). After discussion with EOWG Co-Chairs, I propose adding this wording to the **bottom** of all sub-pages:

> The law or policy links above go to official versions that may not be very accessible. If you know of more accessible versions, please let us know through the **[submission form](https://www.w3.org/WAI/policies/submission/)** or e-mail to [wai-eo-editors@w3.org](mailto:wai-eo-editors@w3.org).

**Comment by slhenry** [comment]
3. For few that we know are totally inaccessible (so far only Russian one), I think we want to put at the top of the page:

> At least one of links below goes to an official version is not accessible. If you know of more accessible versions, please let us know through the submission form or e-mail to wai-eo-editors@w3.org.

**Comment by slhenry** [comment]
[EOWG input in 28 February telecon](https://www.w3.org/2020/02/28-eo-minutes.html#x04)

**Comment by iadawn** [comment]
#499 adds a disclaimer option for all pages
