### ISSUE TITLE
Updates for this resource

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#389]
Please urgently update this resource to be current, more information can be found in this thread on the WAI IG Mailinglist: https://lists.w3.org/Archives/Public/w3c-wai-ig/2020JulSep/0010.html

Alternatively, provide a simple list with Country -> Link to Policy if the current format is too hard to maintain. Find-ability of this information is incredibly important for the adaption of accessibility in practice and the Laws and Policies resource is out of date for over two years, years that brought major changes in Europe and other countries.

**Comment by maryjom** [comment]
FYI the  California Consumer Privacy Act referenced in this email is a proposed law, and has gone back for editing (the WCAG version they will require is not known and it isn't known if it will come back for approval this legislative session). IMO, until it is more firm, suggest not adding it.

The EN does include WCAG 2.1 now and that is it for WCAG 2.1 being required by countries, to my knowledge other than Canada.  Canada is recommending the EN 301 549 V2.2.1 (which includes WCAG 2.1) for procurement of accessible ICT. It is not "required" nor regulated.

**Comment by yatil** [comment]
I mean we do have >40 open issues, and yes, some of those are just stubs. Even the EU text has not been updated in years. We have an open issue from November 2018(!) and there has happened quite a lot in the meantime, namely the European Accessibility Act. (#344)

Sure we can say that that is only a little updating, but it needs to be done. And there seems to be just a lot of red tape. See #388, for example. A well known expert with data from the country they are working in, providing said data in the format that can be published immediately. And it is not done. 

That’s one reason why I have not bothered to submit the data for Germany. It’s sitting there in an issue (#380), I just need to write it up. But why shall I, or anyone, put in all the work with the almost certain knowledge that it will take months until it shows up on the website, if at all. It’s highly discouraging.

I don’t want to sound discouraging (although my disappointment is clear). The promise of this resource is enormous, but if data is not published, it is useless. And I put dozens and dozens, maybe hundreds of hours into it to create the basis, make sure that language switching works and so on. And then there is so little use to it.

**Comment by yatil** [comment]
People on Twitter now ask for alternatives for this resource: https://twitter.com/CerovacBogdan/status/1311265868102488066

**Comment by yatil** [comment]
More calls for updating this resource as it creates loads of confusion: https://twitter.com/roelvangils/status/1392064802898563074

**Comment by iadawn** [comment]
Thanks for the comments, just to say that we will be continuing to support this resource. The last couple of months has seen a concerted effort to reduce the backlog of issues and pull requests. Additionally there are resources available to continue updating this resource throughout 2023.

The W3C WAI list specifically supports people wanting to find laws and policies that reference W3C standards.

Lainey's list is excelllent and she provides valuable commentary and a broader scope that it wouldn't be appropriate for W3C to add.
