### ISSUE TITLE
Definitions - private sector

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#4]
Should we split this into 'for-profit' an 'not-for-profit'?

@maryjom drafted:
> Private sector -  Businesses and organizations that are not part of the public sector

**Comment by slhenry** [comment]
That was my first reaction; however, in the policy context, I don't think the distinction is relevant.

**Comment by yatil** [comment]
This is a hard one anyway. In Austria, for example, the accessibility law applies to the private sector but only if they have consumer as clients, not for B2B stuff. Accessibility at the workplace is covered by another law and encompasses both B2C and B2B.

Laws are complex.

**Comment by maryjom** [comment]
Removed the "non-profit" sentence and only mention it (not has a hard rule) in the definition.  Reopen the issue with alternate suggestions if the definition is still problematic.
