### ISSUE TITLE
Create Form

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#41]
In relation to #18

**Comment by iamjolly** [comment]
See my [comment](https://github.com/w3c/wai-policies-prototype/issues/18#issuecomment-290611658) on #18

**Comment by iamjolly** [comment]
* @iamjolly will create form handler script with validation
* @yatil will upload PHP form handler script on the W3C servers with some validation (provided by @iamjolly)
* @yatil and @iamjolly will test and troubleshoot with @maryjom

**Comment by iamjolly** [comment]
Form created with [PR88](https://github.com/w3c/wai-policies-prototype/pull/88).
PHP handler script will be edited next.

**Comment by iamjolly** [comment]
Form has been created and form handler is also created. Other issues can be opened to address specific form-related concerns.
