### ISSUE TITLE
[high-medium] add note that not all listed in filter count

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-policies-prototype#417]
In the filter items here [Law and Policy Overview Table](https://www.w3.org/WAI/policies/#xtable>) , it lists the numbers for each. However, we are not requiring that data for all submissions, per [Minimum Required Information for Policy Publishing](https://www.w3.org/WAI/EO/wiki/Policies_Workflow#Minimum_Required_Information_for_Policy_Publishing). Therefore, the numbers are misleading.

**We probably should add a sentence clarifying that.**

_(/me 's writing hat not here right now, so not able to draft idea yet.)_

_(re: labels: it's not programming bug, but it is a UI communication bug)_

**Comment by brewerj** [comment]
@shawna-slh Wouldn't the simplest statement be to add, after "Filter policies to show" a parenthetical phrase stating "(may not include all policies)"

If you mean something other than that, please clarify, thanks.

**Comment by iadawn** [comment]
@shawna-slh Or we could just remove the numbers?
