### ISSUE TITLE
Information from the EU

### ISSUE THREAD

**Issue by AlainVagner** [w3c/wai-policies-prototype#418]
Maybe these two pages can help in updating this content:
- the list of national transposition measures concerning the Web Accessibility directive: https://eur-lex.europa.eu/legal-content/EN/NIM/?uri=CELEX:32016L2102
- the list of Member states' bodies in charge of monitoring the Web Accessibility directive https://digital-strategy.ec.europa.eu/en/policies/web-accessibility-monitoring

**Comment by brewerj** [comment]
@EricVelleman have you and Vera captured the relevant data from Alain's linked list of transposed standards? If so, shall we reply and close this?

**Comment by iadawn** [comment]
Details have been captured and I also included a link to these two documents in the European Union page
