### ISSUE TITLE
Recently updated indicator

### ISSUE THREAD

**Issue by yatil** [w3c/wai-policies-prototype#42]
From the February 28 F2F:
Mark entries updated in the last six months and in the last three months.

**Comment by slhenry** [comment]
fyi, I'm not convinced this is overall a good thing...

**Comment by yatil** [comment]
Can we get a straw poll if we need this. It is fairly easy to implement, and it would be auto-updating (thanks to JavaScript), so if we don’t update it, the indicators just disappear (or rather: get not applied).

**Comment by iamjolly** [comment]
@yatil and @slhenry - I like the idea of a "freshness indicator" for policies, provided it doesn't create any maintenance work to remove it. Sounds like that is the case with a JS-based approach. 

I feel like the design of this will determine how much of a good thing it will be helpful and unobtrusive being my factors for what "good" is for this).

**Comment by iamjolly** [comment]
Consensus at F2F is to close this for now and can open a new issue if there is good reason for this feature.
