### ISSUE TITLE
Broken links on United States policy page

### ISSUE THREAD

**Issue by VeraLange** [w3c/wai-policies-prototype#431]
The following links were found to be broken. The access-board page was updated, which led to many broken links.
I have tried to track down relevant resources and found these replacement links. Please double-check them and replace the links on this policy page: https://www.w3.org/WAI/policies/united-states/

**Link 1:** https://section508.gov/content/quick-reference-guide , replace with: https://www.section508.gov/manage/laws-and-policies/quick-reference-guide/

**Link 2:** https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-telecommunications-act-guidelines/guidance-on-the-telecommunications-act-%C2%A7255-guidelines/ , replace with: https://www.access-board.gov/ict/guide/2555_guide.md.html

**Link 3:** https://www.access-board.gov/the-board/laws/telecommunications-act/ , replace with: https://www.access-board.gov/law/ta.html

**Link 4:** https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-telecommunications-act-guidelines/section-255-guidelines/ , replace with: https://www.federalregister.gov/documents/2000/12/21/00-32017/electronic-and-information-technology-accessibility-standards

**Link 5:** https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/guide-to-the-section-508-standards/ , I cannot find a replacement to this link, so far.

**Link 6:** https://www.section508.gov/section-508-of-the-rehabilitation-act , replace with: https://www.access-board.gov/ict/

**Link 7:** http://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-section-508-standards/section-508-standards , replace with: https://www.access-board.gov/ict/#about-the-ict-accessibility-standards

**Comment by iadawn** [comment]
Replaced all identified links. Removed the reference to Guide to the Section 508 Standards as I couldn't locate a replacement for this.
