### ISSUE TITLE
[minor] pager bug

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-policies-prototype#477]
There is an empty "pager" at the bottom.

```<nav class="pager" aria-label="Previous/Next Page">```

Shows an empty box:
![image](https://user-images.githubusercontent.com/6991814/217985072-e0101568-6655-4e79-8889-dc4cd564eed9.png)

Elsewhere on the WAI site, there are pagers such as these:
![image](https://user-images.githubusercontent.com/6991814/217985310-d9e991ad-69c1-4bad-b9b2-3c6f9a2a21a1.png)

Looking at previous builds from Netlify, I don't see that we had a pager on these policy pages -- so maybe there was some thought to it previously and recent updates uncommented out some code or some such?

**Comment by iadawn** [comment]
This was removed in 13f8135

Change is currently ready to deploy and can be reviewed in https://master--wai-policies-prototype.netlify.app/policies/
