### ISSUE TITLE
checklinks for all

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-policies-prototype#481]
e.g. [Korea link report](https://validator.w3.org/checklink?url=https://www.w3.org/WAI/policies/republic-of-korea/)

**Comment by iadawn** [comment]
Checking:

* [Preview with all new additions](https://validator.w3.org/checklink?uri=https%3A%2F%2Fdeploy-preview-495--wai-policies-prototype.netlify.app%2Fpolicies%2F&hide_type=all&recursive=on&depth=1&check=Check)
* [Preview with updates to existing countries](https://validator.w3.org/checklink?uri=https%3A%2F%2Fdeploy-preview-496--wai-policies-prototype.netlify.app%2Fpolicies%2F&hide_type=all&recursive=on&depth=1&check=Check)

I double checked the [offending link](https://www.law.go.kr/%EB%B2%95%EB%A0%B9/%EC%9E%A5%EC%95%A0%EC%9D%B8%EC%B0%A8%EB%B3%84%EA%B8%88%EC%A7%80%EB%B0%8F%EA%B6%8C%EB%A6%AC%EA%B5%AC%EC%A0%9C%EB%93%B1%EC%97%90%EA%B4%80%ED%95%9C%EB%B2%95%EB%A5%A0) that was identified on the Republic of Korea page and it doesn't appear to be reporting 404 now.
