### ISSUE TITLE
icons in table [was: Summary Table: Weekly Survey Question/Comments]

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-policies-prototype#49]
This is for the EOWG Weekly Survey: Let us know what you think about the summary table and what advice or opinions you have to make it better.

**Comment by yatil** [comment]
(This is probably controversial and I _don’t_ feel strongly.) It would be awesome if we could use icons for certain information to make the information denser. For example for law, we could use a § sign, proposed law would be (§)… This would mean we need a legend, but I think if the primary use of the table is to be skimmable, it might be worth it.

**Comment by bakkenb** [comment]
I like the amount of data in the Summary Table. I am sure that I will have different opinions of the layout and how it is presented once it is moved into the final draft design that will be used for the resource. That said, I think the set is correct.

I like the idea of adding icons on this resource for things that could/should be skim-able. Not added just for looks, but added when appropriate and would help the content be more intuitive.

**Comment by maryjom** [comment]
I know some would like icons and some won't based on previous conversations I've heard on the EOWG.  My recollection is that Shawn and Sharron are not fans of icons.

**Comment by yatil** [comment]
Seeing the table as it is now, I don’t think it needs icons. If you asked me, you can close the issue.

**Comment by slhenry** [comment]
+1 to close this issue

**Comment by iamjolly** [comment]
Closing. Thanks all!
