### ISSUE TITLE
Disclaimer text is on different line from the expand/collapse arrow.

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#59]
This is related to Issue #1, but when the collapsible functionality was added, the expand/collapse icon appears a line above the disclaimer heading.

**Comment by iamjolly** [comment]
fixed with commit https://github.com/w3c/wai-policies-prototype/commit/b741224d08b996fc92edcd3f59ecd73d4584293e (copied @yatil's inline style for heading element)
