### ISSUE TITLE
Summary table - status

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#6]
@maryjom asked: How do we indicate difference between Law on books vs. adopted by EU member states vs. enforced with a standard in place?

**Comment by AndrewArch** [comment]
Also, 'policies' in preparation / proposed such as the Australian adoption of the European EN301549

**Comment by sharronrush** [comment]
Isn't that exactly what the 'status' column does? Or is there another level of adoption/enforcement to be indicated?

**Comment by slhenry** [comment]
+1 to Sharron

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item05)

**Comment by maryjom** [comment]
This change has been made in the prototype and there is general agreement that the enacted date scheme works with draft items having the text "draft".
