### ISSUE TITLE
Need method to add related page link to link to state/province info

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#61]
Right now on all countries there's the blanket message pointer "Related page: Australian states..." as a placeholder for links to a separate state/province page.  This functionality will need to be added so we can begin to prototype those pages as well and in the meantime we can point to the existing state/province page.  

Note: The "Related page" label shouldn't show up when there is no related page to point to.

**Comment by iamjolly** [comment]
@yatil will take a look at how the file structure should be set up and then @iamjolly will take that and run with it

**Comment by iamjolly** [comment]
@maryjom and I discussed this one and we will only have one related page per country (at this time) and I'll work on a way to use Kramdown/Markdown to have a URL with linked text (title of the page).

**Comment by iamjolly** [comment]
Hi @maryjom - This is now working with both Canada and United States files as examples. 

To add/edit related pages for countries, you'll need to add the following to the files:
```
relatedpages:
    - title: The Title of the Related Page
      url: https://the-url-to-that-related-page
```

This will allow us to add multiple related pages just like we can add multiple documents for each policy.
