### ISSUE TITLE
Expand all on page and expand all per country functionality

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#62]
If we have expand/collapse on each of the laws & policies for each country (which I like), there should be an easy one-button method to expand all for the whole page, and another on each country to expand all for just that country.  WCAG has similar methods for expanding/collapsing info.

**Comment by slhenry** [comment]
Issue moot because each country will be on separate pages.

Closed in discussion with Mary Jo and others. :-)
