### ISSUE TITLE
Disclaimer link no longer shows up at bottom of page

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#69]
We had added a disclaimer link at the bottom of the page, but it disappeared when the new (or old) WAI template/CSS was applied.  Need to make sure that when the final template is applied the link is re-added.

**Comment by iamjolly** [comment]
@maryjom - We have the disclaimer in the Introduction section at the top of the page. Was the other disclaimer link to this section/heading near the top of the page, or was it linking to a different file/location?
