### ISSUE TITLE
non-legally binding policies/strategies

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#8]
How to handle non-legally binding policies / strategies / standards?

@maryjom said: [in relation to the Australian [NTS](http://www.finance.gov.au/publications/wcag-2-implementation/) and [Digital Service Standard](https://www.dto.gov.au/standard/9-make-it-accessible/)] These aren’t really required by this law [Australia's Disability Discrimination Act], but the government does have a policy to make their websites accessible – though it seems to be on a voluntary basis.

**Comment by sharronrush** [comment]
would this not be indicated in Status column by indicating Policy rather than Legally Mandated

**Comment by slhenry** [comment]
Agree that it would be good to clearly indicate non-legally binding, verses legally-binding. Perhaps @brewerj  and @nitedog have suggestions for wording...

**Comment by AndrewArch** [comment]
and sometimes legally binding applies to different sectors (corporate vs govt vs educations etc) and for different issues (physical vs digital)

**Comment by slhenry** [comment]
Discussion in [10 Feb telecon](https://www.w3.org/2017/02/10-eo-minutes.html#item07)

**Comment by maryjom** [comment]
Marking it as a "recommendation" or "policy" helps some. Recommended when they clearly state it is "voluntary" or "should" type of language.  Policy is more of a "must follow" but it doesn't necessarily have a law behind it.  I think I made the verbiage and definitions clearer in this case. Reopen with suggested changes if you feel it isn't properly explained or used.
