### ISSUE TITLE
Hong kong is showing up first in the alphabetic list of countries

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#81]
Not sure why, but Hong kong is now showing up first in the left navigation list and first in the alphabetic table when sorted alphabetically, and first in the alphabetized countries at the bottom - before the countries that start with earlier letters.

**Comment by iamjolly** [comment]
Looking at this now @maryjom

**Comment by iamjolly** [comment]
Hmmm. After publishing changes, it is fixed locally but not on the live prototype.

**Comment by iamjolly** [comment]
OK. This is now fixed in [my last commit](https://github.com/w3c/wai-policies-prototype/commit/5a326af59bea675a636ceb0c9390ebdd379c5636).
