### ISSUE TITLE
Country details page needs linkage back to main page (or similar navigation as main page)

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#86]
I showed the policy prototype to someone and when they navigated to a specific country's page, they noticed there's no breadcrumb or navigation to get back (other than the browser's back button). I'm thinking we should have the country navigation menu (left nav) in all of the individual country pages as well as the main page.

**Comment by iamjolly** [comment]
Excellent suggestion and I agree! I'll see what I can do to add navigation to the country pages.
