### ISSUE TITLE
Responsible body

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-policies-prototype#9]
@maryjom suggests: Pick word applicable to that country. U.S. says “Agency”, other countries seem to say “Ministry”

**Comment by AndrewArch** [comment]
In Australia we generally have Departments and Agencies, Eg Dept of Finance or Attorney-General’s Department _and_ Digital Transformation Agency.

**Comment by bakkenb** [comment]
Do we pick this word (wording) or do we just use the words that are input by the user? I am not sure what the question or issue is here. More explanation please.

**Comment by slhenry** [comment]
I think we'll need multiple words to cover most cases.

**Comment by yatil** [comment]
Can’t we say something like “Issuer”? (Is a law issued? I have no idea…) For example:

* Issuer: Dept of Finance
* Issuer: Attorney-General’s Department and Digital Transformation Agency
* Issuer: Bundesministerium für Arbeit und Soziales

As the type of Agency is in its name, this should be sufficient. In Germany, having “Ministry” and then “Arbeit und Soziales” would not work as there are federal (“Bundes“) and state (“Landes”) ministries. Having something more neutral might help.

**Comment by maryjom** [comment]
Some of these agencies are the issuer, some are responsible for enablement, and some are responsible for enforcement. e.g. for Section 508 in the U.S., the U.S. Access Board develops and issues the rule.  GSA is responsible for ensuring or educating agencies use the Section 508 standard in procurement. Dept. of Justice gets involved with enforcement and development of settlement agreements when non-compliance issues are not resolved.  

I think the best solution would be to have the choice in the submission form and have the correct term show up in the content as suggested by Shawn.  Terms to include in the choices: Agency, Ministry, Department.  Can you think of any others?

**Comment by slhenry** [comment]
Is it important to distinguish between Agency, Ministry, or Department? Will people submitting information necessarily know which category is right for their information?

If not very important to distinguish, then I support a generic term. To make it understandable, we could do something like:

> Responsible entities (Agency, Ministry, etc.)

**Comment by maryjom** [comment]
@slhenry I don't think it's important to distinguish, so actually would prefer to use something generic. It also means it's one less thing to have to put into the form and verify before posting an update.

**Comment by iamjolly** [comment]
This has been addressed in the latest pull request for the submission form [PR88](https://github.com/w3c/wai-policies-prototype/pull/88). Closing, but issue can be reopened if wording should be revisited.
