### ISSUE TITLE
Checkbox Fieldsets and Legends

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-policies-prototype#90]
Policy filter subtitles need to be legends.  They need to relate to the checkboxes they own, rather than being siblings to their checkboxes.

A legend and its checkboxes must be wrapped in a fieldset.

This is of importance because screen-reader users often jump directly into form fields non linearly.  They will have no idea what the checkbox is for.

They will hear for example "WCAG 1.0 checkbox not checked". with no understanding of what this checkbox relates to.

Bonus, by using fieldset and legend, as well as nesting your checkboxes in their labels you will no longer need to use list items for these.  Woo hoo! :-)

Here is an example:
```
<fieldset>
    <legend><span class="screen-reader-text">Filter policies to show: </span>Standard</legend>
    <label><input id="wcag10" type="checkbox">WCAG 1.0</label>
    <label><input id="wcag10d" type="checkbox">WCAG 1.0 derivative</label>
    ...
</fieldset>
<fieldset>
    <legend><span class="screen-reader-text">Filter policies to show: </span>Status</legend>
    <label><input id="proposed" type="checkbox">Proposed/in development</label>
    <label><input id="in_effect" type="checkbox">In effect</label>
</fieldset>
...
```
Now they will hear "Filter policies to show: Standard. WCAG 1.0. Checkbox. Not checked".

(note I also added some screen-reader text to flesh out the legend for even more understanding)

**Comment by iamjolly** [comment]
Thanks for these notes @haltersweb. Once we start work on wiring up the filters for real, we'll address this issue. Should be addressed during week of 4/24/2017.
