### ISSUE TITLE
Policy submission form - class of visuallyhidden content still visible on the page

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-policies-prototype#94]
There are leftover headings that have a class="visuallyhidden" that are visible (not hidden) on the submission form page.  Do we really even need these headings now that we are using fieldsets?

**Comment by iamjolly** [comment]
Hmmm. Those were cloned from how the WAI-Tools submission form was set up. I don't know why the headings were used in addition to the fieldset legends, but I suspect it was to add another layer of navigation. I say we can either remove them or change the class to "no-display" which is the equivalent in CSS as the WAI-Tools class for "visuallyhidden".
